# This file was generated by GoReleaser. DO NOT EDIT.
cask "cronkit" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "f891da4e79b0590cae335a0266f390a2b65680f4465611c02d3884499b3718d5"
      url "https://github.com/hzerrad/cronkit/releases/download/v#{version}/cronkit_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4ee09855f56322ff6cfaa27c738f2ff8f295532e9c044f9b3d8ce8ba468d704d"
      url "https://github.com/hzerrad/cronkit/releases/download/v#{version}/cronkit_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f4bdcbc5ccb927d7a4408580ebb198e5963fff786769ff7637f09c874c93361b"
      url "https://github.com/hzerrad/cronkit/releases/download/v#{version}/cronkit_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2b09253786d5fab97ac61744fe55571da88af9c2db789ace4be3a77b9e57520a"
      url "https://github.com/hzerrad/cronkit/releases/download/v#{version}/cronkit_linux_arm64.tar.gz"
    end
  end

  name "cronkit"
  desc "Make cron human again - CLI tool for cron job management"
  homepage "https://github.com/hzerrad/cronkit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cronkit"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cronkit"]
    end
  end

  # No zap stanza required

end
