# This file was generated by GoReleaser. DO NOT EDIT.
cask "cronkit" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "a4013379a8711930e39cc6a7eba447c78d249a4c4beb797346d11f2fbddb39ea"
      url "https://github.com/hzerrad/cronkit/releases/download/v#{version}/cronkit_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "60e7bb2840ccbb910cfc97ab45816ab8570bb2e32c0176458042c68631895b96"
      url "https://github.com/hzerrad/cronkit/releases/download/v#{version}/cronkit_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f9f8013084f8d006e0e9240005846499ff2d19c34938dfe139c96dfba927ecca"
      url "https://github.com/hzerrad/cronkit/releases/download/v#{version}/cronkit_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5edf246375f58d2a6200580a217d3256e1a04ebaa7c064f59c5165390d0ee0fc"
      url "https://github.com/hzerrad/cronkit/releases/download/v#{version}/cronkit_linux_arm64.tar.gz"
    end
  end

  name "cronkit"
  desc "Make cron human again - CLI tool for cron job management"
  homepage "https://github.com/hzerrad/cronkit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cronkit"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cronkit"]
    end
  end

  # No zap stanza required

end
