# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cronic < Formula
  desc "Make cron human again - CLI tool for cron job management"
  homepage "https://github.com/hzerrad/cronic"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hzerrad/cronic/releases/download/v0.1.0/cronic_darwin_amd64.tar.gz"
      sha256 "9183e14a6331aab6fb54034b007581a6bf2c0107611cf14dec29e163af827ca0"

      def install
        bin.install "cronic"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hzerrad/cronic/releases/download/v0.1.0/cronic_darwin_arm64.tar.gz"
      sha256 "c12db602d8d85a6ba126d7e7fd920348b0cbee1589fd7c90fb4d10508171941c"

      def install
        bin.install "cronic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hzerrad/cronic/releases/download/v0.1.0/cronic_linux_amd64.tar.gz"
      sha256 "9cf702f388925eae49f2868bdc479d2e050fdafc50fb36d11096d4ce87105f14"
      def install
        bin.install "cronic"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hzerrad/cronic/releases/download/v0.1.0/cronic_linux_arm64.tar.gz"
      sha256 "725de62cc01d315935de1a41527197d4a0ac4bd99836aba195d5a7d1741b0609"
      def install
        bin.install "cronic"
      end
    end
  end

  test do
    system "#{bin}/cronic", "version"
  end
end
