# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cronic < Formula
  desc "Make cron human again - CLI tool for cron job management"
  homepage "https://github.com/hzerrad/cronic"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hzerrad/cronic/releases/download/v0.1.0/cronic_darwin_amd64.tar.gz"
      sha256 "109b235bb75a3f7bb64acbba78626c2140cb042956465f0c10fc617552dff3de"

      def install
        bin.install "cronic"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hzerrad/cronic/releases/download/v0.1.0/cronic_darwin_arm64.tar.gz"
      sha256 "399633727502d5a12c2e002931ced2e2103862e1e57f984cfc004eab28b99c0c"

      def install
        bin.install "cronic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hzerrad/cronic/releases/download/v0.1.0/cronic_linux_amd64.tar.gz"
      sha256 "4fbec0bc351e3f5e4abfb2449687d40e97c93bc4e2a9feb943f4c01bdd4dd71f"
      def install
        bin.install "cronic"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hzerrad/cronic/releases/download/v0.1.0/cronic_linux_arm64.tar.gz"
      sha256 "e503f085af3799788efa28f23628d92a2f0e2740154b56cb885d94890f7648fd"
      def install
        bin.install "cronic"
      end
    end
  end

  test do
    system "#{bin}/cronic", "version"
  end
end
