# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cronkit < Formula
  desc "Make cron human again - CLI tool for cron job management"
  homepage "https://github.com/hzerrad/cronkit"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hzerrad/cronkit/releases/download/v0.1.0/cronkit_darwin_amd64.tar.gz"
      sha256 "63dcb660ea0be61f87e88149359b4b856d41edfd9f4bccc9e04a6ecd021b00f8"

      def install
        bin.install "cronkit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hzerrad/cronkit/releases/download/v0.1.0/cronkit_darwin_arm64.tar.gz"
      sha256 "bdc62b216f3dbdb7773460aad4e113cc228da4da421cc76cd3bdcbfdf696f4dc"

      def install
        bin.install "cronkit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hzerrad/cronkit/releases/download/v0.1.0/cronkit_linux_amd64.tar.gz"
      sha256 "ab748cad99914b98b4095bae0204a2e2637427009f05b21fe3a37b36e3f0a1fe"
      def install
        bin.install "cronkit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hzerrad/cronkit/releases/download/v0.1.0/cronkit_linux_arm64.tar.gz"
      sha256 "7319d4bd94ac0369867c8df21bb0023d9407ddefc34ac72d8b8c6f323f832a2f"
      def install
        bin.install "cronkit"
      end
    end
  end

  test do
    system "#{bin}/cronkit", "version"
  end
end
