# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cronkit < Formula
  desc "Make cron human again - CLI tool for cron job management"
  homepage "https://github.com/hzerrad/cronkit"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hzerrad/cronkit/releases/download/v0.1.0/cronkit_darwin_amd64.tar.gz"
      sha256 "55eec9489ca3c72937bd8f4951466891d7ccdb591d1d581af26653ec48150c56"

      def install
        bin.install "cronkit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hzerrad/cronkit/releases/download/v0.1.0/cronkit_darwin_arm64.tar.gz"
      sha256 "6a8cc774023edfcd8f1ed34b064804eb749d6cc77612367ce08b03e3d3f46697"

      def install
        bin.install "cronkit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hzerrad/cronkit/releases/download/v0.1.0/cronkit_linux_amd64.tar.gz"
      sha256 "5838de3b03b6026b5c7d5109d903a07be690c0b9813ee6631575f937293d49a8"
      def install
        bin.install "cronkit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hzerrad/cronkit/releases/download/v0.1.0/cronkit_linux_arm64.tar.gz"
      sha256 "860c828d4578809102ddab3f0a35de2d82c1deccb2c9481c1e0cdff2b8620d82"
      def install
        bin.install "cronkit"
      end
    end
  end

  test do
    system "#{bin}/cronkit", "version"
  end
end
