# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cronic < Formula
  desc "Make cron human again - CLI tool for cron job management"
  homepage "https://github.com/hzerrad/cronic"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hzerrad/cronic/releases/download/v0.1.0/cronic_darwin_amd64.tar.gz"
      sha256 "63e14410e17ba16f00582537f91c526a022ac41c84b6ad00e83a968c51666e6f"

      def install
        bin.install "cronic"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hzerrad/cronic/releases/download/v0.1.0/cronic_darwin_arm64.tar.gz"
      sha256 "bcea09acc502a6b5503cddac6498da3c897ee703a02d797d1701a479841c50e6"

      def install
        bin.install "cronic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hzerrad/cronic/releases/download/v0.1.0/cronic_linux_amd64.tar.gz"
      sha256 "0e67f792dab0232a40f724e882b221764928ad0cb6a0604b747d03703d094476"
      def install
        bin.install "cronic"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hzerrad/cronic/releases/download/v0.1.0/cronic_linux_arm64.tar.gz"
      sha256 "6299d1bc8e53c800fbf668c8e4c5a74dc42aae56885eb71e53ccf1e5a1170eef"
      def install
        bin.install "cronic"
      end
    end
  end

  test do
    system "#{bin}/cronic", "version"
  end
end
