# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cronkit < Formula
  desc "Make cron human again - CLI tool for cron job management"
  homepage "https://github.com/hzerrad/cronkit"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hzerrad/cronkit/releases/download/v0.1.1/cronkit_darwin_amd64.tar.gz"
      sha256 "e2130ade883a5f3be2e4403a1a0cbb82f72151b282fd5a49f5dcd963bae00d5f"

      define_method(:install) do
        bin.install "cronkit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hzerrad/cronkit/releases/download/v0.1.1/cronkit_darwin_arm64.tar.gz"
      sha256 "00835a7d0e310b862b94848345c6accb5da9712d622e706bc1396627a52e6c7b"

      define_method(:install) do
        bin.install "cronkit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hzerrad/cronkit/releases/download/v0.1.1/cronkit_linux_amd64.tar.gz"
      sha256 "d8592d72551aabd932c0e0272007c6396210be2d296afb14d72bdddf7ab9321e"
      define_method(:install) do
        bin.install "cronkit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hzerrad/cronkit/releases/download/v0.1.1/cronkit_linux_arm64.tar.gz"
      sha256 "0e64c9334c70c6c52071cc2319683fd0390f3d9ff9973204493bb077e3ee449b"
      define_method(:install) do
        bin.install "cronkit"
      end
    end
  end

  test do
    system "#{bin}/cronkit", "version"
  end
end
